### PR TITLE
particle system

### PR DESCRIPTION
**Pull request by ChongYing**
particle system

### CODE REVIEW

**Comment by EthanGA** [comment]
Hi CY,

There are some conflicts between this branch and the master. Sync your master, update this branch from master, and then you can fix the conflicts.

**Comment by ChongYing** [comment]
My unity was broken once... T T

**Comment by ChongYing** [comment]
There's a lot I have to do that manually, so give me some time.

**Comment by EthanGA** [comment]
No worries CY! Sorry for the hassle :(

On Sat, Apr 16, 2016 at 8:00 PM, ChongYing notifications@github.com wrote:

> There's a lot I have to do that manually, so give me some time.
> 
> Sent from my iPhone
> 
> > On Apr 16, 2016, at 7:51 PM, EthanGA notifications@github.com wrote:
> > 
> > Hi CY,
> > 
> > There are some conflicts between this branch and the master. Sync your
> > master, update this branch from master, and then you can fix the conflicts.
> > 
> > ―
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/TeamHoldOn/Hold-On/pull/103#issuecomment-210925928

## 

Ethan Goss-Alexander

**Comment by ChongYing** [comment]
BTW, I don't see many enemies. Actually I only see one. Are you doing this
purposely for now?

**Comment by EthanGA** [comment]
Yeah, it will start with just one. Then after the scripted sequence there
will be more.

On Sat, Apr 16, 2016 at 8:41 PM, ChongYing notifications@github.com wrote:

> BTW, I don't see many enemies. Actually I only see one. Are you doing this
> purposely for now?
> 
> On Sat, Apr 16, 2016 at 8:25 PM, EthanGA notifications@github.com wrote:
> 
> > No worries CY! Sorry for the hassle :(
> > 
> > On Sat, Apr 16, 2016 at 8:00 PM, ChongYing notifications@github.com
> > wrote:
> > 
> > > There's a lot I have to do that manually, so give me some time.
> > > 
> > > Sent from my iPhone
> > > 
> > > > On Apr 16, 2016, at 7:51 PM, EthanGA notifications@github.com
> > > > wrote:
> > > > 
> > > > Hi CY,
> > > > 
> > > > There are some conflicts between this branch and the master. Sync
> > > > your
> > > > master, update this branch from master, and then you can fix the
> > > > conflicts.
> > > > 
> > > > ―
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > 
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/TeamHoldOn/Hold-On/pull/103#issuecomment-210925928
> > 
> > ## 
> > 
> > Ethan Goss-Alexander
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/TeamHoldOn/Hold-On/pull/103#issuecomment-210927449
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/TeamHoldOn/Hold-On/pull/103#issuecomment-210932584

## 

Ethan Goss-Alexander

**Pull request closed without merging**
